# -*- coding: utf-8 -*-
"""kernel_launch_overhead.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gK9z_K1oiYC-SorBW7kqFc-Gjmj8pnTU
"""

# ══════════════════════════════════════════════════════════════
#  Kernel launch overhead, measured live on a T4
# ══════════════════════════════════════════════════════════════

import time
import torch
import torch.nn.functional as NF

dev, dt = "cuda", torch.float16
print("GPU:", torch.cuda.get_device_name(0))

# ── 1. Raw per-op cost: 10k tiny adds, compute ≈ 0 ────────────────
x = torch.randn(1, device=dev)
for _ in range(1000): x + 1   # warmup
torch.cuda.synchronize()

N = 10_000
t0 = time.perf_counter()
for _ in range(N): x + 1
torch.cuda.synchronize()
us_per_op = (time.perf_counter() - t0) / N * 1e6
print(f"\n[1] per-op cost, compute≈0: {us_per_op:.1f} µs  (Python + dispatch + launch)")

# ── 2. A fake decode step: same shape as a 7B model's ─────────────
# 32 layers × (2 norms, 4 attn GEMV, 3 FFN GEMV, silu/mul/adds)
# ≈ 14 kernels/layer ≈ 450 launches per token. Dims shrunk from
# 4096/11008 to 1024/2730 just to fit easily on a T4 — smaller
# kernels make the overhead share even MORE extreme than 17%.

H, FI, L = 1024, 2730, 32
Wa = [torch.randn(4, H, H, device=dev, dtype=dt) for _ in range(L)]   # Q,K,V,O
Wg = [torch.randn(FI, H,  device=dev, dtype=dt) for _ in range(L)]    # gate
Wu = [torch.randn(FI, H,  device=dev, dtype=dt) for _ in range(L)]    # up
Wd = [torch.randn(H, FI,  device=dev, dtype=dt) for _ in range(L)]    # down

def decode_step(tok):
  for i in range(L):
      h = NF.layer_norm(tok, (H,))
      q, k, v, o = (torch.matmul(h, Wa[i][j].t()) for j in range(4))
      tok = tok + o
      h = NF.layer_norm(tok, (H,))
      g = torch.matmul(h, Wg[i].t())
      u = torch.matmul(h, Wu[i].t())
      tok = tok + torch.matmul(NF.silu(g) * u, Wd[i].t())
  return tok

tok = torch.randn(1, H, device=dev, dtype=dt)

for _ in range(5): decode_step(tok)               # warmup (cuBLAS init)
torch.cuda.synchronize()

steps = 50
t0 = time.perf_counter()
for _ in range(steps): decode_step(tok)
torch.cuda.synchronize()
eager_ms = (time.perf_counter() - t0) / steps * 1e3

# ── 3. Same step, captured as a CUDA Graph ────────────────────────
s = torch.cuda.Stream()                           # warmup on a side stream
s.wait_stream(torch.cuda.current_stream())
with torch.cuda.stream(s):
    for _ in range(3): decode_step(tok)
torch.cuda.current_stream().wait_stream(s)

g = torch.cuda.CUDAGraph()
with torch.cuda.graph(g):
  static_out = decode_step(tok)

for _ in range(5): g.replay()                     # warmup replay
torch.cuda.synchronize()

t0 = time.perf_counter()
for _ in range(steps): g.replay()
torch.cuda.synchronize()
graph_ms = (time.perf_counter() - t0) / steps * 1e3

print(f"\n[2] eager : {eager_ms:5.2f} ms/token  ({1000/eager_ms:4.0f} tok/s)")
print(f"[3] graph : {graph_ms:5.2f} ms/token  ({1000/graph_ms:4.0f} tok/s)   same math → {eager_ms/graph_ms:.1f}× faster")
print(f"    tax ≈ {us_per_op:.1f} µs × ~450 launches ≈ {us_per_op*450/1000:.1f} ms of the {eager_ms:.1f} ms eager step")

from torch.profiler import profile, ProfilerActivity
with profile(activities=[ProfilerActivity.CUDA]) as prof:
    decode_step(tok); torch.cuda.synchronize()
rows = [e for e in prof.key_averages() if e.self_device_time_total > 0]
busy_ms = sum(e.self_device_time_total for e in rows) / 1e3
print(f"{sum(e.count for e in rows)} device kernels per step")
print(f"GPU busy: {busy_ms:.2f} ms   eager wall: {eager_ms:.2f} ms")
print(f"→ GPU idle-waiting-for-launches for {100*(1-busy_ms/eager_ms):.0f}% of the step")